// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("https://qa.aegishrms.com/sign-in")
    await driver.manage().window().setRect({ width: 1040, height: 984 })
    await driver.findElement(By.id("email")).sendKeys("jacks@gmail.com")
    await driver.findElement(By.id("password")).sendKeys("Pass@1234")
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.id("email"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.css(".group")).click()
    {
      const element = await driver.findElement(By.css(".group"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
